#!/usr/bin/env python

import sys
import os

# main: main function
def main(argv):
    file = argv[0]
    f = open(file, 'r')
    for line in f:
        print(line, end=' ')

    f.close()
    print("\n.\n.\n.\ndone printing.")


if __name__ == "__main__":
    main(sys.argv[1:])