#!/usr/bin/env python

import sys
import os

# main: main function
def main(argv):
    file = argv[0]
    file2 = argv[1]
    f = open(file, 'r')
    f2 = open(file2,'w')

    for line in f:
        print(line, end=' ')
        
    f2.close()
    f.close()
    
    print("\n.\n.\n.\ndone printing.")


if __name__ == "__main__":
    main(sys.argv[1:])