#!/usr/bin/env python

import os
import sys
import numpy as np

def dot_product(vectors):
	if len(vectors[0]) != len(vectors[1]):
		print("the vectors are not the same length.\n")
		return False
	try:
		a = vectors[0]
		b = vectors[1]
	except:
		print("the vectors contain non-numbers.\n")
		return False

	scalar = np.dot(a,b)
	return scalar

def main(argv):

	vectors = []

	if len(argv) == 2:
		file = argv[0]

		if ".txt" not in argv[0]:
			print("first argument should be a txt file.\n")
			return 0

		try:
			const = float(argv[1])
		except:
			print("second argument should be a number.\n")
			sys.exit()
	else:
		print("need two arguments in this order:")
		print("<file.txt> <constant>\n")
		return 0

	try:
		with open(file,'r') as f:
			for line in f:
				line = line.strip()
				line = line.split(', ')
				try:
					vectors.append(list(map(float,line)))
				except:
					print("error: file contains non-numbers")
					sys.exit()
	except:
		print("error: invalid file.")
		sys.exit()

	scalar = dot_product(vectors)

	if scalar is False:
		return 0
	else:
		print("x = ", vectors[0])
		print("y = ", vectors[1])
		print("z = ", scalar + const)
		print()

if __name__ == "__main__":
	main(sys.argv[1:])


